apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: teq-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: 605134445572.dkr.ecr.us-east-2.amazonaws.com/theessentialquo/theessentialquo-product-service:latest
        ports:
        - containerPort: 8082
        readinessProbe:
          httpGet: { path: /product/actuator/health/readiness, port: 8082 }
          initialDelaySeconds: 5
        livenessProbe:
          httpGet: { path: /product/actuator/health/liveness, port: 8082 }
          initialDelaySeconds: 10
        resources:
          requests: { cpu: "100m", memory: "256Mi" }
          limits:   { cpu: "500m", memory: "512Mi" }
