apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: teq-dev
spec:
  type: LoadBalancer  # for quick testing; later use Ingress/ALB Controller
  selector:
    app: product
  ports:
    - port: 80
      targetPort: 8082
